config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :employees
  devise_for :users
  resources :messages do
    member do
      post :edit
    end
  end
  resources :posts
  get 'my_posts', to: 'posts#my_posts'
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#home"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <%= link_to "Rails Blog", root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:'nav-link'%>
        </li>
        
      </ul>
      <ul class = "navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- 
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <%#<% if user_signed_in? %>
      <%#<%= current_user.email %>
      <!-- link_to 'Log out' not working -->
      <%#<%= button_to 'Log out', destroy_user_session_path, method: :delete %>
      <%#<%= link_to 'Account Settings', edit_user_registration_path %>

    <%#<% else %>
      <%#<%= link_to 'Log in', new_user_session_path %>
      <%#<%= link_to 'Sign up', new_user_registration_path %>
    <%#<% end %>
   <main class="container mx-auto mt-28 px-5 flex">
      <%= turbo_frame_tag "modal" %>
      <%= link_to "Employees", employees_path %>
      <%= Time.zone.now %>
      <hr class="my-4">
      <%= yield %>
    </main>
  </body>
</html>